### ISSUE TITLE
Add mysql-client

### ISSUE THREAD

**Issue by Breee** [uniget-org/tools#6195]
- brew reference:  https://github.com/Homebrew/homebrew-core/blob/47fe0f1860f73ffe393074de1b749ac8a0e0ee10/Formula/m/mysql-client.rb
- docker reference:  https://github.com/Logiqx/mysql-client/blob/master/Dockerfile

**Comment by nicholasdille** [comment]
This is a tricky one... The homebrew formula uses a tarball which is linked from nowhere (or my google-fu is bad).

The mysql homepage does not list specific client packages.

I would have to build from the source repo and see how to use the result.

Let me meditate on this 🧘

**Comment by nicholasdille** [comment]
This is not going anywhere. Looking at the alpine package `mysql-client` this is way to complicated.
